# Generated by Django 5.0.7 on 2024-08-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='AttributeKey',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attiribute',
            new_name='attiribute_key',
        ),
    ]
